# Generated by Django 3.2.20 on 2023-07-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tobar', '0002_auto_20230719_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cures',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
