# Generated by Django 3.2.20 on 2023-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well', models.CharField(max_length=100, unique=True)),
                ('townland', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cures', models.CharField(max_length=100)),
            ],
        ),
    ]
