
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-19T14:50:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "45e529905d6b4baf11b655c90851c5d0ef333e82",
 "version": "1.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
